/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgMedicos;

import com.mycompany.cadconsultas.classes.Medico;
import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONMedicosService;
import com.mycompany.cadconsultas.listas.ListMedicos;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgEditMedicos extends javax.swing.JDialog {
    private final ListMedicos medicosCadastrados;
    private Medico editedMedico;
    
    /**
     * Creates new form DlgEditMedicos
     * @param parent
     * @param modal
     * @param medicosCadastrados
     */
    public DlgEditMedicos(java.awt.Frame parent, boolean modal, ListMedicos medicosCadastrados) {
        super(parent, modal);
        initComponents();
        
        this.medicosCadastrados = medicosCadastrados;
        this.edtMedicosCadastrados.setText(this.medicosCadastrados.toString());
        this.editedMedico = new Medico();
        this.clearCampos();
        this.enableCampos(false);
        
    }
    
    private void saveToJSON() {
        String path = "Medicos.json";
        String data = JSONMedicosService.medicosToJSON(this.medicosCadastrados);
        FilePersistence.saveToFile(data, path);
    }
    
    private void clearCampos() {
        this.edtEditedCrm.setText("");
        this.edtHorariosDisponiveis.setText("");
        this.edtEspecialidade.setText("");
        this.edtName.setText("");
        this.edtCrm.setText("");
    }
    
    private void enableCampos(boolean flag) {
        this.edtEditedCrm.setEditable(!flag);
        this.edtHorariosDisponiveis.setEditable(flag);
        this.edtEspecialidade.setEditable(flag);
        this.edtName.setEditable(flag);
        this.edtCrm.setEditable(flag);
    }
    
    private void MedicoToCampos(Medico edited) {
        if (edited != null) {
            this.edtHorariosDisponiveis.setText(edited.getHorariosDisponiveis());
            this.edtEspecialidade.setText(edited.getEspecialidade());
            this.edtName.setText(edited.getName());
            this.edtCrm.setText(edited.getCrm());
            this.enableCampos(true);
        } else {
            JOptionPane.showMessageDialog(this, "Esse médico não está cadastrado");
        }
    }
    
    private Medico camposToMedico() {
        Medico newData = new Medico();
        
        newData.setEspecialidade(this.edtEspecialidade.getText());
        newData.setHorariosDisponiveis(this.edtHorariosDisponiveis.getText());
        newData.setName(this.edtName.getText());
        newData.setCrm(this.edtCrm.getText());
        
        return newData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCrmMedicoEditado = new javax.swing.JPanel();
        lblEditedCrm = new javax.swing.JLabel();
        edtEditedCrm = new javax.swing.JTextField();
        painelCampos = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        lblCrm = new javax.swing.JLabel();
        edtCrm = new javax.swing.JTextField();
        lblEspecialidade = new javax.swing.JLabel();
        edtEspecialidade = new javax.swing.JTextField();
        lblHorariosDisponiveis = new javax.swing.JLabel();
        edtHorariosDisponiveis = new javax.swing.JTextField();
        painelTitleMedicosCadastrados = new javax.swing.JPanel();
        lblTitleMedicosCadastrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtMedicosCadastrados = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("EDITANDO OS DADOS DOS MÉDICOS");
        painelTitle.add(lblTitle);

        lblEditedCrm.setText("CRM do médico que vai ser editado");

        edtEditedCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEditedCrmActionPerformed(evt);
            }
        });

        lblName.setText("Nome");

        edtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNameActionPerformed(evt);
            }
        });

        lblCrm.setText("CRM");

        lblEspecialidade.setText("Especialidade");

        lblHorariosDisponiveis.setText("Horários disponíveis");

        edtHorariosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtHorariosDisponiveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCamposLayout = new javax.swing.GroupLayout(painelCampos);
        painelCampos.setLayout(painelCamposLayout);
        painelCamposLayout.setHorizontalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblHorariosDisponiveis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHorariosDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblCrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCrm))
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtName))
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtEspecialidade))))
        );
        painelCamposLayout.setVerticalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrm)
                    .addComponent(edtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidade)
                    .addComponent(edtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorariosDisponiveis)
                    .addComponent(edtHorariosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCrmMedicoEditadoLayout = new javax.swing.GroupLayout(painelCrmMedicoEditado);
        painelCrmMedicoEditado.setLayout(painelCrmMedicoEditadoLayout);
        painelCrmMedicoEditadoLayout.setHorizontalGroup(
            painelCrmMedicoEditadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCrmMedicoEditadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCrmMedicoEditadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditedCrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtEditedCrm))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(painelCrmMedicoEditadoLayout.createSequentialGroup()
                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelCrmMedicoEditadoLayout.setVerticalGroup(
            painelCrmMedicoEditadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCrmMedicoEditadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditedCrm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEditedCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleMedicosCadastrados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleMedicosCadastrados.setText("MÉDICOS CADASTRADOS");
        painelTitleMedicosCadastrados.add(lblTitleMedicosCadastrados);

        edtMedicosCadastrados.setColumns(20);
        edtMedicosCadastrados.setRows(5);
        jScrollPane1.setViewportView(edtMedicosCadastrados);
        this.edtMedicosCadastrados.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnSave.setText("SALVAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        painelBtns.add(btnSave);

        btnEdit.setText("EDITAR");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        painelBtns.add(btnEdit);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelCrmMedicoEditado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(97, 97, 97))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitleMedicosCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleMedicosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCrmMedicoEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtEditedCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEditedCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEditedCrmActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String choicedCrm = this.edtEditedCrm.getText();
        this.editedMedico = this.medicosCadastrados.findMedicoByCrm(choicedCrm);
        this.MedicoToCampos(this.editedMedico);
    }//GEN-LAST:event_btnEditActionPerformed

    private void edtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNameActionPerformed

    private void edtHorariosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtHorariosDisponiveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtHorariosDisponiveisActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Medico newData = this.camposToMedico();
        
        if (this.medicosCadastrados.edit(this.editedMedico.getCrm(), newData)) {
            JOptionPane.showMessageDialog(this, "Médico editado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível editar esse médico");
        }
        
        this.enableCampos(false);
        this.clearCampos();
        this.edtMedicosCadastrados.setText(this.medicosCadastrados.toString());
        this.saveToJSON();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
        this.enableCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField edtCrm;
    private javax.swing.JTextField edtEditedCrm;
    private javax.swing.JTextField edtEspecialidade;
    private javax.swing.JTextField edtHorariosDisponiveis;
    private javax.swing.JTextArea edtMedicosCadastrados;
    private javax.swing.JTextField edtName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCrm;
    private javax.swing.JLabel lblEditedCrm;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblHorariosDisponiveis;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleMedicosCadastrados;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelCrmMedicoEditado;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleMedicosCadastrados;
    // End of variables declaration//GEN-END:variables
}
