/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgMedicos;

import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONMedicosService;
import com.mycompany.cadconsultas.listas.ListMedicos;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgRemoveMedicos extends javax.swing.JDialog {
    private final ListMedicos medicosCadastrados;
    
    /**
     * Creates new form DlgRemoveMedicos
     * @param parent
     * @param modal
     * @param medicosCadastrados
     */
    public DlgRemoveMedicos(java.awt.Frame parent, boolean modal, ListMedicos medicosCadastrados) {
        super(parent, modal);
        initComponents();
        
        this.medicosCadastrados = medicosCadastrados;
        this.clearCampos();
        this.edtMedicosCadastrados.setText(this.medicosCadastrados.toString());
    }
    
    private void clearCampos() {
        this.edtRemovedCrm.setText("");
    }
    
    private void saveToJSON() {
        String path = "Medicos.json";
        String data = JSONMedicosService.medicosToJSON(this.medicosCadastrados);
        FilePersistence.saveToFile(data, path);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCrmMedicoRemovido = new javax.swing.JPanel();
        lblRemovedCrm = new javax.swing.JLabel();
        edtRemovedCrm = new javax.swing.JTextField();
        painelTitleMedicosCadastrados = new javax.swing.JPanel();
        lblTitleMedicosCadastrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtMedicosCadastrados = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("REMOVENDO MÉDICOS");
        painelTitle.add(lblTitle);

        lblRemovedCrm.setText("CRM do médico que vai ser removido");

        edtRemovedCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRemovedCrmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCrmMedicoRemovidoLayout = new javax.swing.GroupLayout(painelCrmMedicoRemovido);
        painelCrmMedicoRemovido.setLayout(painelCrmMedicoRemovidoLayout);
        painelCrmMedicoRemovidoLayout.setHorizontalGroup(
            painelCrmMedicoRemovidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCrmMedicoRemovidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCrmMedicoRemovidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRemovedCrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtRemovedCrm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCrmMedicoRemovidoLayout.setVerticalGroup(
            painelCrmMedicoRemovidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCrmMedicoRemovidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemovedCrm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtRemovedCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleMedicosCadastrados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleMedicosCadastrados.setText("MÉDICOS CADASTRADOS");
        painelTitleMedicosCadastrados.add(lblTitleMedicosCadastrados);

        edtMedicosCadastrados.setColumns(20);
        edtMedicosCadastrados.setRows(5);
        jScrollPane1.setViewportView(edtMedicosCadastrados);
        this.edtMedicosCadastrados.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnRemove.setText("REMOVER");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        painelBtns.add(btnRemove);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelCrmMedicoRemovido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitleMedicosCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleMedicosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCrmMedicoRemovido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtRemovedCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRemovedCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRemovedCrmActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String crmRemovido = this.edtRemovedCrm.getText();
        
        if (this.medicosCadastrados.remove(crmRemovido)) {
            JOptionPane.showMessageDialog(this, "Médico removido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Esse médico não foi cadastrado no sistema");
        }
        
        this.clearCampos();
        this.edtMedicosCadastrados.setText(this.medicosCadastrados.toString());
        this.saveToJSON();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JTextArea edtMedicosCadastrados;
    private javax.swing.JTextField edtRemovedCrm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRemovedCrm;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleMedicosCadastrados;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCrmMedicoRemovido;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleMedicosCadastrados;
    // End of variables declaration//GEN-END:variables
}
