/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadconsultas.gui;

import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONConsultasService;
import com.mycompany.cadconsultas.file.JSONMedicosService;
import com.mycompany.cadconsultas.file.JSONPacientesService;
import com.mycompany.cadconsultas.gui.dlg.dlgConsultas.DlgCadConsultas;
import com.mycompany.cadconsultas.gui.dlg.dlgMedicos.DlgCadMedicos;
import com.mycompany.cadconsultas.gui.dlg.dlgPaciente.DlgCadPacientes;
import com.mycompany.cadconsultas.listas.ListConsultas;
import com.mycompany.cadconsultas.listas.ListMedicos;
import com.mycompany.cadconsultas.listas.ListPacientes;



/**
 *
 * @author piva
 */
public class FrHome extends javax.swing.JFrame {
    private ListConsultas consultasCadastradas;
    private ListMedicos medicosCadastrados;
    private ListPacientes pacientesCadastrados;
    
    
    /**
     * Creates new form FrHome
     */
    public FrHome() {
        initComponents();
        
        this.consultasCadastradas = new ListConsultas();
        this.medicosCadastrados = new ListMedicos();
        this.pacientesCadastrados = new ListPacientes();
        
        
        
        this.JSONToLists();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelOptions = new javax.swing.JPanel();
        btnConsultas = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("GERENCIADOR DE CONSULTAS");
        painelTitle.add(lblTitle);

        painelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        btnConsultas.setText("CONSULTAS");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        painelOptions.add(btnConsultas);

        btnPacientes.setText("PACIENTES");
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        painelOptions.add(btnPacientes);

        btnMedicos.setText("MÉDICOS");
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });
        painelOptions.add(btnMedicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JSONToLists() {
        String filePathConsulta = "Consultas.json";
        String consultasData = FilePersistence.loadFromFile(filePathConsulta);
        if (!consultasData.isEmpty())
            this.consultasCadastradas = JSONConsultasService.JSONToConsultas(consultasData);
        
        String filePathMedicos = "Medicos.json";
        String medicosData = FilePersistence.loadFromFile(filePathMedicos);
        if (!medicosData.isEmpty())
            this.medicosCadastrados = JSONMedicosService.JSONToMedicos(medicosData);
        
        String filePathPacientes = "Pacientes.json";
        String pacientesData = FilePersistence.loadFromFile(filePathPacientes);
        if (!pacientesData.isEmpty())
            this.pacientesCadastrados = JSONPacientesService.JSONToPacientes(pacientesData);
    }
    
    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        DlgCadMedicos medicosScreen = new DlgCadMedicos(this, true, this.medicosCadastrados);
        medicosScreen.setVisible(true);
    }//GEN-LAST:event_btnMedicosActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        DlgCadPacientes pacientesScreen = new DlgCadPacientes(this, true, this.pacientesCadastrados);
        pacientesScreen.setVisible(true);
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        DlgCadConsultas consultasScreen = new DlgCadConsultas(this, true, consultasCadastradas, medicosCadastrados, pacientesCadastrados);
        consultasScreen.setVisible(true);
    }//GEN-LAST:event_btnConsultasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel painelOptions;
    private javax.swing.JPanel painelTitle;
    // End of variables declaration//GEN-END:variables
}
