/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas.dlgConsultasEdit;

import com.mycompany.cadconsultas.classes.Consulta;
import com.mycompany.cadconsultas.classes.Paciente;
import com.mycompany.cadconsultas.listas.ListPacientes;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgEditConsultasPacientes extends javax.swing.JDialog {
    private final Consulta editedConsulta;
    private final ListPacientes pacientesCadastrados;
    
    /**
     * Creates new form DlgRemovePacientes
     * @param parent
     * @param modal
     * @param pacientesCadastrados
     * @param editedConsulta
     */
    public DlgEditConsultasPacientes(java.awt.Frame parent, boolean modal, ListPacientes pacientesCadastrados, Consulta editedConsulta) {
        super(parent, modal);
        initComponents();
        
        this.editedConsulta = editedConsulta;
        this.pacientesCadastrados = pacientesCadastrados;
        this.clearCampos();
        this.edtPacientesCadastrados.setText(this.pacientesCadastrados.toString());
    }
    
    private void clearCampos() {
        this.edtAtribuidoCpf.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCpfPacienteAtribuido = new javax.swing.JPanel();
        lblAtribuidoCpf = new javax.swing.JLabel();
        edtAtribuidoCpf = new javax.swing.JTextField();
        painelTitlePacientesCadastrados = new javax.swing.JPanel();
        lblTitlePacientesCadastrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtPacientesCadastrados = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnAtribuir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("ATRIBUINDO UM PACIENTE PARA A CONSULTA");
        painelTitle.add(lblTitle);

        lblAtribuidoCpf.setText("CPF do paciente que vai ser a atribuido");

        edtAtribuidoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAtribuidoCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCpfPacienteAtribuidoLayout = new javax.swing.GroupLayout(painelCpfPacienteAtribuido);
        painelCpfPacienteAtribuido.setLayout(painelCpfPacienteAtribuidoLayout);
        painelCpfPacienteAtribuidoLayout.setHorizontalGroup(
            painelCpfPacienteAtribuidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCpfPacienteAtribuidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCpfPacienteAtribuidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAtribuidoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtAtribuidoCpf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCpfPacienteAtribuidoLayout.setVerticalGroup(
            painelCpfPacienteAtribuidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCpfPacienteAtribuidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtribuidoCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtAtribuidoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitlePacientesCadastrados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitlePacientesCadastrados.setText("PACIENTES CADASTRADOS");
        painelTitlePacientesCadastrados.add(lblTitlePacientesCadastrados);

        edtPacientesCadastrados.setColumns(20);
        edtPacientesCadastrados.setRows(5);
        jScrollPane1.setViewportView(edtPacientesCadastrados);
        this.edtPacientesCadastrados.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnAtribuir.setText("ATRIBUIR");
        btnAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtribuirActionPerformed(evt);
            }
        });
        painelBtns.add(btnAtribuir);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelCpfPacienteAtribuido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitlePacientesCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitlePacientesCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCpfPacienteAtribuido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtAtribuidoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAtribuidoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAtribuidoCpfActionPerformed

    private void btnAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtribuirActionPerformed
       String cpfAtribuido = this.edtAtribuidoCpf.getText();
       Paciente atribuido = this.pacientesCadastrados.findPacienteByCpf(cpfAtribuido);
       
       if (atribuido != null) {
           this.editedConsulta.setPaciente(atribuido);
           JOptionPane.showMessageDialog(this, "Paciente foi atribuido com sucesso!");
       } else {
           JOptionPane.showMessageDialog(this, "Esse paciente não está cadastrado no sistema");
       }
    }//GEN-LAST:event_btnAtribuirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtribuir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField edtAtribuidoCpf;
    private javax.swing.JTextArea edtPacientesCadastrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtribuidoCpf;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitlePacientesCadastrados;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCpfPacienteAtribuido;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitlePacientesCadastrados;
    // End of variables declaration//GEN-END:variables
}
