/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas.dlgConsultasEdit;

import com.mycompany.cadconsultas.classes.Consulta;
import com.mycompany.cadconsultas.listas.ListConsultas;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgEditConsultasDadosGerais extends javax.swing.JDialog {
    private final Consulta editedConsulta;
    private final ListConsultas consultasCadastradas;
    
    /**
     * Creates new form DlgEditProfessores
     * @param parent
     * @param modal
     * @param editedConsulta
     * @param consultasCadastradas
     */
    public DlgEditConsultasDadosGerais(java.awt.Frame parent, boolean modal, Consulta editedConsulta, ListConsultas consultasCadastradas) {
        super(parent, modal);
        initComponents();
        this.consultasCadastradas = consultasCadastradas;
        this.editedConsulta = editedConsulta;
        
        this.edtConsultasCadastradas.setText(this.consultasCadastradas.toString());
        this.voltarCamposOriginal();
    }
    
    
    private void voltarCamposOriginal() {
        this.edtData.setText(this.editedConsulta.getData());
        this.edtId.setText(this.editedConsulta.getId());
    }
    
   
    private void consultaToCampos(Consulta edited) {
        if (edited != null) {
            this.edtData.setText(edited.getData());
            this.edtId.setText(edited.getId());
        } else {
            JOptionPane.showMessageDialog(this, "Esse aluno não está cadastrado");
        }
    }
    
    private Consulta camposToConsulta() {
        Consulta newData = new Consulta();
        
        newData.setData(this.edtData.getText());
        newData.setId(this.edtId.getText());
       
        return newData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelTitleConsultasCadastradas = new javax.swing.JPanel();
        lblTitleConsultasCadastradas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtConsultasCadastradas = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        painelCampos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("EDITANDO OS DADOS GERAIS DA CONSULTA");
        painelTitle.add(lblTitle);

        lblTitleConsultasCadastradas.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleConsultasCadastradas.setText("CONSULTAS CADASTRADAS");
        painelTitleConsultasCadastradas.add(lblTitleConsultasCadastradas);

        edtConsultasCadastradas.setColumns(20);
        edtConsultasCadastradas.setRows(5);
        jScrollPane1.setViewportView(edtConsultasCadastradas);
        this.edtConsultasCadastradas.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnSave.setText("SALVAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        painelBtns.add(btnSave);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        lblId.setText("ID");

        edtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdActionPerformed(evt);
            }
        });

        lblData.setText("Data");

        javax.swing.GroupLayout painelCamposLayout = new javax.swing.GroupLayout(painelCampos);
        painelCampos.setLayout(painelCamposLayout);
        painelCamposLayout.setHorizontalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtId))
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtData, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
        );
        painelCamposLayout.setVerticalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 164, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Consulta newData = this.camposToConsulta();
        
        if (this.consultasCadastradas.edit(this.editedConsulta.getId(), newData)) {
            JOptionPane.showMessageDialog(this, "Consulta editada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível editar essa consulta");
        }
        
        this.voltarCamposOriginal();
        this.edtConsultasCadastradas.setText(this.consultasCadastradas.toString());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.voltarCamposOriginal();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextArea edtConsultasCadastradas;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleConsultasCadastradas;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleConsultasCadastradas;
    // End of variables declaration//GEN-END:variables
}
