/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas.dlgConsultasEdit;

import com.mycompany.cadconsultas.classes.Consulta;
import com.mycompany.cadconsultas.listas.ListConsultas;
import com.mycompany.cadconsultas.listas.ListMedicos;
import com.mycompany.cadconsultas.listas.ListPacientes;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgEditConsultas extends javax.swing.JDialog {
    private final ListConsultas consultasCadastradas;
    private final ListMedicos medicosCadastrados;
    private final ListPacientes pacientesCadastrados;
    private final JFrame frParent;
    
    
    /**
     * Creates new form DlgEditConsultas
     * @param parent
     * @param modal
     * @param consultasCadastradas
     * @param medicosCadastrados
     * @param pacientesCadastrados
     */
    public DlgEditConsultas(java.awt.Frame parent, boolean modal, ListConsultas consultasCadastradas, ListMedicos medicosCadastrados, ListPacientes pacientesCadastrados) {
        super(parent, modal);
        initComponents();
        
        this.consultasCadastradas = consultasCadastradas;
        this.medicosCadastrados = medicosCadastrados;
        this.pacientesCadastrados = pacientesCadastrados;
        this.frParent = (JFrame) parent;
        
        this.edtConsultasCadastradas.setText(this.consultasCadastradas.toString());
    }

    private void clearCampos() {
        this.edtEditedId.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelIdConsultaEditada = new javax.swing.JPanel();
        lblEditedId = new javax.swing.JLabel();
        edtEditedId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtConsultasCadastradas = new javax.swing.JTextArea();
        painelTitleConsultasCadastradas = new javax.swing.JPanel();
        lblTitleConsultasCadastradas = new javax.swing.JLabel();
        painelBtns = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("EDITANDO OS DADOS DAS CONSULTAS");
        painelTitle.add(lblTitle);

        lblEditedId.setText("ID da consulta que vai ser editada");

        edtEditedId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEditedIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelIdConsultaEditadaLayout = new javax.swing.GroupLayout(painelIdConsultaEditada);
        painelIdConsultaEditada.setLayout(painelIdConsultaEditadaLayout);
        painelIdConsultaEditadaLayout.setHorizontalGroup(
            painelIdConsultaEditadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIdConsultaEditadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelIdConsultaEditadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditedId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtEditedId))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        painelIdConsultaEditadaLayout.setVerticalGroup(
            painelIdConsultaEditadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIdConsultaEditadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditedId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEditedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        edtConsultasCadastradas.setColumns(20);
        edtConsultasCadastradas.setRows(5);
        jScrollPane1.setViewportView(edtConsultasCadastradas);
        this.edtConsultasCadastradas.setEditable(false);

        lblTitleConsultasCadastradas.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleConsultasCadastradas.setText("CONSULTAS CADASTRADAS");
        painelTitleConsultasCadastradas.add(lblTitleConsultasCadastradas);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnEdit.setText("EDITAR");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        painelBtns.add(btnEdit);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelIdConsultaEditada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelIdConsultaEditada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 549, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtEditedIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEditedIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEditedIdActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String editedId = this.edtEditedId.getText();
        Consulta editedConsulta = this.consultasCadastradas.findConsultaById(editedId);
        
        if (editedConsulta != null) {
            this.setVisible(false);
            DlgEditConsultasOptions screenConsultasEditOptions = new DlgEditConsultasOptions(frParent, true, consultasCadastradas, editedConsulta, medicosCadastrados, pacientesCadastrados);
            screenConsultasEditOptions.setVisible(true);
            this.edtConsultasCadastradas.setText(this.consultasCadastradas.toString());
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Essa consulta não foi cadastrada");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JTextArea edtConsultasCadastradas;
    private javax.swing.JTextField edtEditedId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditedId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleConsultasCadastradas;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelIdConsultaEditada;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleConsultasCadastradas;
    // End of variables declaration//GEN-END:variables
}
