/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas.dlgConsultasEdit;

import com.mycompany.cadconsultas.classes.Consulta;
import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONConsultasService;
import com.mycompany.cadconsultas.listas.ListConsultas;
import com.mycompany.cadconsultas.listas.ListMedicos;
import com.mycompany.cadconsultas.listas.ListPacientes;
import javax.swing.JFrame;

/**
 *
 * @author piva
 */
public class DlgEditConsultasOptions extends javax.swing.JDialog {
    private final ListConsultas consultasCadastradas;
    private final Consulta editedConsulta;
    private final ListMedicos medicosCadastrados;
    private final ListPacientes pacientesCadastrados;
    private final JFrame frParent;
    
    
    /**
     * Creates new form DlgCadConsultas
     * @param parent
     * @param modal
     * @param consultasCadastradas
     * @param editedConsulta
     * @param medicosCadastrados
     * @param pacientesCadastrados
     */
    public DlgEditConsultasOptions(java.awt.Frame parent, boolean modal, ListConsultas consultasCadastradas, Consulta editedConsulta, ListMedicos medicosCadastrados, ListPacientes pacientesCadastrados) {
        super(parent, modal);
        initComponents();
        
        this.consultasCadastradas = consultasCadastradas;
        this.editedConsulta = editedConsulta; 
        this.medicosCadastrados = medicosCadastrados;
        this.pacientesCadastrados = pacientesCadastrados;
        this.frParent = (JFrame) parent;
    }

    private void saveToJSON() {
        String path = "Consultas.json";
        String data = JSONConsultasService.consultasToJSON(this.consultasCadastradas);
        FilePersistence.saveToFile(data, path);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelOptions = new javax.swing.JPanel();
        btnDadosGerais = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("ESCOLHA A OPÇÃO QUE VAI SER EDITADA");
        painelTitle.add(lblTitle);

        painelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        btnDadosGerais.setText("DADOS GERAIS");
        btnDadosGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosGeraisActionPerformed(evt);
            }
        });
        painelOptions.add(btnDadosGerais);

        btnPacientes.setText("PACIENTES");
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        painelOptions.add(btnPacientes);

        btnMedicos.setText("MÉDICOS");
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });
        painelOptions.add(btnMedicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadosGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosGeraisActionPerformed
        this.setVisible(false);
        DlgEditConsultasDadosGerais screenEditConsultasDadosGerais = new DlgEditConsultasDadosGerais(frParent, true, editedConsulta, consultasCadastradas);
        screenEditConsultasDadosGerais.setVisible(true);
        this.setVisible(true);
        this.saveToJSON();
    }//GEN-LAST:event_btnDadosGeraisActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        this.setVisible(false);
        DlgEditConsultasPacientes screenEditConsultasPacientes = new DlgEditConsultasPacientes(frParent, true, pacientesCadastrados, editedConsulta);
        screenEditConsultasPacientes.setVisible(true);
        this.setVisible(true);
        this.saveToJSON();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
       this.setVisible(false);
       DlgEditConsultasMedico screenEditMedicos = new DlgEditConsultasMedico(frParent, rootPaneCheckingEnabled, medicosCadastrados, editedConsulta);
       screenEditMedicos.setVisible(true);
       this.setVisible(true);
       this.saveToJSON();
    }//GEN-LAST:event_btnMedicosActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDadosGerais;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel painelOptions;
    private javax.swing.JPanel painelTitle;
    // End of variables declaration//GEN-END:variables
}
