/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas.dlgConsultasEdit;

import com.mycompany.cadconsultas.classes.Consulta;
import com.mycompany.cadconsultas.classes.Medico;
import com.mycompany.cadconsultas.listas.ListMedicos;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgEditConsultasMedico extends javax.swing.JDialog {
    private final Consulta editedConsulta;
    private final ListMedicos medicosCadastrados;
    
    /**
     * Creates new form DlgRemoveMedicos
     * @param parent
     * @param modal
     * @param medicosCadastrados
     * @param editedConsulta
     */
    public DlgEditConsultasMedico(java.awt.Frame parent, boolean modal, ListMedicos medicosCadastrados, Consulta editedConsulta) {
        super(parent, modal);
        initComponents();
        
        this.editedConsulta = editedConsulta;
        this.medicosCadastrados = medicosCadastrados;
        this.clearCampos();
        this.edtMedicosCadastrados.setText(this.medicosCadastrados.toString());
    }
    
    private void clearCampos() {
        this.edtAtribuidoCrm.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCrmMedicoAtribuido = new javax.swing.JPanel();
        lblAtribuidoCrm = new javax.swing.JLabel();
        edtAtribuidoCrm = new javax.swing.JTextField();
        painelTitleMedicosCadastrados = new javax.swing.JPanel();
        lblTitleMedicosCadastrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtMedicosCadastrados = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnAtribuir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("ATRIBUINDO UM MÉDICO PARA A CONSULTA");
        painelTitle.add(lblTitle);

        lblAtribuidoCrm.setText("CRM do médico que vai ser a atribuido");

        edtAtribuidoCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAtribuidoCrmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCrmMedicoAtribuidoLayout = new javax.swing.GroupLayout(painelCrmMedicoAtribuido);
        painelCrmMedicoAtribuido.setLayout(painelCrmMedicoAtribuidoLayout);
        painelCrmMedicoAtribuidoLayout.setHorizontalGroup(
            painelCrmMedicoAtribuidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCrmMedicoAtribuidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCrmMedicoAtribuidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAtribuidoCrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtAtribuidoCrm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCrmMedicoAtribuidoLayout.setVerticalGroup(
            painelCrmMedicoAtribuidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCrmMedicoAtribuidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtribuidoCrm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtAtribuidoCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleMedicosCadastrados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleMedicosCadastrados.setText("MÉDICOS CADASTRADOS");
        painelTitleMedicosCadastrados.add(lblTitleMedicosCadastrados);

        edtMedicosCadastrados.setColumns(20);
        edtMedicosCadastrados.setRows(5);
        jScrollPane1.setViewportView(edtMedicosCadastrados);
        this.edtMedicosCadastrados.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnAtribuir.setText("ATRIBUIR");
        btnAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtribuirActionPerformed(evt);
            }
        });
        painelBtns.add(btnAtribuir);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelCrmMedicoAtribuido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitleMedicosCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleMedicosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCrmMedicoAtribuido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtAtribuidoCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAtribuidoCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAtribuidoCrmActionPerformed

    private void btnAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtribuirActionPerformed
       String crmAtribuido = this.edtAtribuidoCrm.getText();
       Medico atribuido = this.medicosCadastrados.findMedicoByCrm(crmAtribuido);
       
       if (atribuido != null) {
           this.editedConsulta.setMedico(atribuido);
           JOptionPane.showMessageDialog(this, "Medico foi atribuido com sucesso!");
       } else {
           JOptionPane.showMessageDialog(this, "Esse medico não está cadastrado no sistema");
       }
    }//GEN-LAST:event_btnAtribuirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtribuir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField edtAtribuidoCrm;
    private javax.swing.JTextArea edtMedicosCadastrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtribuidoCrm;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleMedicosCadastrados;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCrmMedicoAtribuido;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleMedicosCadastrados;
    // End of variables declaration//GEN-END:variables
}
