/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgPaciente;

import com.mycompany.cadconsultas.classes.Paciente;
import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONPacientesService;
import com.mycompany.cadconsultas.listas.ListPacientes;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgEditPacientes extends javax.swing.JDialog {
    private final ListPacientes pacientesCadastrados;
    Paciente editedPaciente;
    
    /**
     * Creates new form DlgEditPacientes
     * @param parent
     * @param modal
     * @param pacientesCadastrados
     */
    public DlgEditPacientes(java.awt.Frame parent, boolean modal, ListPacientes pacientesCadastrados) {
        super(parent, modal);
        initComponents();
        
        this.pacientesCadastrados = pacientesCadastrados;
        this.edtPacientesCadastrados.setText(this.pacientesCadastrados.toString());
        this.editedPaciente = new Paciente();
        this.clearCampos();
        this.enableCampos(false);
        
    }
    
    private void saveToJSON() {
        String path = "Pacientes.json";
        String data = JSONPacientesService.pacientesToJSON(this.pacientesCadastrados);
        FilePersistence.saveToFile(data, path);
    }
    
    private void clearCampos() {
        this.edtEditedCpf.setText("");
        this.edtCpf.setText("");
        this.edtHistoricoMedico.setText("");
        this.edtName.setText("");
        this.edtDataNascimento.setText("");
    }
    
    private void enableCampos(boolean flag) {
        this.edtEditedCpf.setEditable(!flag);
        this.edtCpf.setEditable(flag);
        this.edtHistoricoMedico.setEditable(flag);
        this.edtName.setEditable(flag);
        this.edtDataNascimento.setEditable(flag);
    }
    
    private void pacienteToCampos(Paciente edited) {
        if (edited != null) {
            this.edtCpf.setText(edited.getCpf());
            this.edtHistoricoMedico.setText(edited.getHistoricoMedico());
            this.edtName.setText(edited.getName());
            this.edtDataNascimento.setText(edited.getDataNascimento());
            this.enableCampos(true);
        } else {
            JOptionPane.showMessageDialog(this, "Esse paciente não está cadastrado");
        }
    }
    
    private Paciente camposToPaciente() {
        Paciente newData = new Paciente();
        
        newData.setHistoricoMedico(this.edtHistoricoMedico.getText());
        newData.setCpf(this.edtCpf.getText());
        newData.setName(this.edtName.getText());
        newData.setDataNascimento(this.edtDataNascimento.getText());
        
        return newData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCpfPacienteEditado = new javax.swing.JPanel();
        lblEditedCpf = new javax.swing.JLabel();
        edtEditedCpf = new javax.swing.JTextField();
        painelCampos = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        edtDataNascimento = new javax.swing.JTextField();
        lblHistoricoMedico = new javax.swing.JLabel();
        edtHistoricoMedico = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        painelTitlePacientesCadastrados = new javax.swing.JPanel();
        lblTitlePacientesCadastrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtPacientesCadastrados = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("EDITANDO OS DADOS DOS PACIENTES");
        painelTitle.add(lblTitle);

        lblEditedCpf.setText("CPF do paciente que vai ser editado");

        edtEditedCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEditedCpfActionPerformed(evt);
            }
        });

        lblName.setText("Nome");

        edtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNameActionPerformed(evt);
            }
        });

        lblDataNascimento.setText("Data de nascimento");

        lblHistoricoMedico.setText("Histórico médico");

        lblCpf.setText("CPF");

        edtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCamposLayout = new javax.swing.GroupLayout(painelCampos);
        painelCampos.setLayout(painelCamposLayout);
        painelCamposLayout.setHorizontalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtDataNascimento)
                        .addContainerGap())
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblHistoricoMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHistoricoMedico)
                        .addContainerGap())
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtName))
                            .addGroup(painelCamposLayout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCpf)))
                        .addGap(6, 6, 6))))
        );
        painelCamposLayout.setVerticalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHistoricoMedico)
                    .addComponent(edtHistoricoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCpfPacienteEditadoLayout = new javax.swing.GroupLayout(painelCpfPacienteEditado);
        painelCpfPacienteEditado.setLayout(painelCpfPacienteEditadoLayout);
        painelCpfPacienteEditadoLayout.setHorizontalGroup(
            painelCpfPacienteEditadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCpfPacienteEditadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCpfPacienteEditadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditedCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtEditedCpf))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(painelCpfPacienteEditadoLayout.createSequentialGroup()
                .addComponent(painelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCpfPacienteEditadoLayout.setVerticalGroup(
            painelCpfPacienteEditadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCpfPacienteEditadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditedCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEditedCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitlePacientesCadastrados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitlePacientesCadastrados.setText("PACIENTES CADASTRADOS");
        painelTitlePacientesCadastrados.add(lblTitlePacientesCadastrados);

        edtPacientesCadastrados.setColumns(20);
        edtPacientesCadastrados.setRows(5);
        jScrollPane1.setViewportView(edtPacientesCadastrados);
        this.edtPacientesCadastrados.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnSave.setText("SALVAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        painelBtns.add(btnSave);

        btnEdit.setText("EDITAR");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        painelBtns.add(btnEdit);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelCpfPacienteEditado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(97, 97, 97))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitlePacientesCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitlePacientesCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCpfPacienteEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtEditedCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEditedCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEditedCpfActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String choicedCpf = this.edtEditedCpf.getText();
        this.editedPaciente = this.pacientesCadastrados.findPacienteByCpf(choicedCpf);
        this.pacienteToCampos(this.editedPaciente);
    }//GEN-LAST:event_btnEditActionPerformed

    private void edtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNameActionPerformed

    private void edtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCpfActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Paciente newData = this.camposToPaciente();
        
        if (this.pacientesCadastrados.edit(this.editedPaciente.getCpf(), newData)) {
            JOptionPane.showMessageDialog(this, "Paciente editado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível editar esse paciente");
        }
        
        this.enableCampos(false);
        this.clearCampos();
        this.edtPacientesCadastrados.setText(this.pacientesCadastrados.toString());
        this.saveToJSON();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
        this.enableCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtDataNascimento;
    private javax.swing.JTextField edtEditedCpf;
    private javax.swing.JTextField edtHistoricoMedico;
    private javax.swing.JTextField edtName;
    private javax.swing.JTextArea edtPacientesCadastrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEditedCpf;
    private javax.swing.JLabel lblHistoricoMedico;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitlePacientesCadastrados;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelCpfPacienteEditado;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitlePacientesCadastrados;
    // End of variables declaration//GEN-END:variables
}
