/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgPaciente;

import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONPacientesService;
import com.mycompany.cadconsultas.listas.ListPacientes;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgRemovePacientes extends javax.swing.JDialog {
    private final ListPacientes pacientesCadastrados;
    
    /**
     * Creates new form DlgRemovePacientes
     * @param parent
     * @param modal
     * @param pacientesCadastrados
     */
    public DlgRemovePacientes(java.awt.Frame parent, boolean modal, ListPacientes pacientesCadastrados) {
        super(parent, modal);
        initComponents();
        
        this.pacientesCadastrados = pacientesCadastrados;
        this.clearCampos();
        this.edtPacienteCadastrados.setText(this.pacientesCadastrados.toString());
    }
    
    private void clearCampos() {
        this.edtRemovedCpf.setText("");
    }
    
    private void saveToJSON() {
        String path = "Pacientes.json";
        String data = JSONPacientesService.pacientesToJSON(this.pacientesCadastrados);
        FilePersistence.saveToFile(data, path);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCpfPacienteRemovido = new javax.swing.JPanel();
        lblRemovedCpf = new javax.swing.JLabel();
        edtRemovedCpf = new javax.swing.JTextField();
        painelTitlePacienteCadastrados = new javax.swing.JPanel();
        lblTitlePacienteCadastrados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtPacienteCadastrados = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("REMOVENDO PACIENTES");
        painelTitle.add(lblTitle);

        lblRemovedCpf.setText("CPF do paciente que vai ser removido");

        edtRemovedCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRemovedCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCpfPacienteRemovidoLayout = new javax.swing.GroupLayout(painelCpfPacienteRemovido);
        painelCpfPacienteRemovido.setLayout(painelCpfPacienteRemovidoLayout);
        painelCpfPacienteRemovidoLayout.setHorizontalGroup(
            painelCpfPacienteRemovidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCpfPacienteRemovidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCpfPacienteRemovidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRemovedCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtRemovedCpf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCpfPacienteRemovidoLayout.setVerticalGroup(
            painelCpfPacienteRemovidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCpfPacienteRemovidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemovedCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtRemovedCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitlePacienteCadastrados.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitlePacienteCadastrados.setText("PACIENTES CADASTRADOS");
        painelTitlePacienteCadastrados.add(lblTitlePacienteCadastrados);

        edtPacienteCadastrados.setColumns(20);
        edtPacienteCadastrados.setRows(5);
        jScrollPane1.setViewportView(edtPacienteCadastrados);
        this.edtPacienteCadastrados.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnRemove.setText("REMOVER");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        painelBtns.add(btnRemove);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelCpfPacienteRemovido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitlePacienteCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitlePacienteCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCpfPacienteRemovido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtRemovedCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRemovedCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRemovedCpfActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String cpfRemovido = this.edtRemovedCpf.getText();
        
        if (this.pacientesCadastrados.remove(cpfRemovido)) {
            JOptionPane.showMessageDialog(this, "Paciente removido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Esse paciente não foi cadastrado no sistema");
        }
        
        this.clearCampos();
        this.edtPacienteCadastrados.setText(this.pacientesCadastrados.toString());
        this.saveToJSON();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JTextArea edtPacienteCadastrados;
    private javax.swing.JTextField edtRemovedCpf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRemovedCpf;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitlePacienteCadastrados;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCpfPacienteRemovido;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitlePacienteCadastrados;
    // End of variables declaration//GEN-END:variables
}
