/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas;

import com.mycompany.cadconsultas.classes.Consulta;
import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONConsultasService;
import com.mycompany.cadconsultas.listas.ListConsultas;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgCreateConsultas extends javax.swing.JDialog {
    ListConsultas consultasCadastradas = new ListConsultas();
    
    
    /**
     * Creates new form DlgAddConsultas
     * @param parent
     * @param modal
     * @param consultasCadastradas
     */
    public DlgCreateConsultas(java.awt.Frame parent, boolean modal, ListConsultas consultasCadastradas) {
        super(parent, modal);
        initComponents();
        
        this.consultasCadastradas = consultasCadastradas;
        this.clearCampos();
        this.edtConsultasCadastradas.setText(consultasCadastradas.toString());
    }
    
    private void saveToJSON() {
        String path = "Consultas.json";
        String data = JSONConsultasService.consultasToJSON(this.consultasCadastradas);
        FilePersistence.saveToFile(data, path);
    }    
    private void clearCampos() {
        this.edtData.setText("");
        this.edtId.setText("");
    }
    
    private Consulta camposToConsulta() {
        Consulta dadosPreenchidos = new Consulta();
 
        dadosPreenchidos.setData(this.edtData.getText());
        dadosPreenchidos.setId(edtId.getText());
        
        return dadosPreenchidos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelCampos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();
        painelConsultasCadastradas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtConsultasCadastradas = new javax.swing.JTextArea();
        painelTitleConsultasCadastradas = new javax.swing.JPanel();
        lblTitleConsultasCadastradas = new javax.swing.JLabel();
        painelBtns = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("CADASTRANDO NOVA CONSULTA");
        painelTitle.add(lblTitle);

        lblId.setText("ID");

        edtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdActionPerformed(evt);
            }
        });

        lblData.setText("Data");

        javax.swing.GroupLayout painelCamposLayout = new javax.swing.GroupLayout(painelCampos);
        painelCampos.setLayout(painelCamposLayout);
        painelCamposLayout.setHorizontalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtData))))
        );
        painelCamposLayout.setVerticalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edtConsultasCadastradas.setColumns(20);
        edtConsultasCadastradas.setRows(5);
        jScrollPane1.setViewportView(edtConsultasCadastradas);
        this.edtConsultasCadastradas.setEditable(false);

        javax.swing.GroupLayout painelConsultasCadastradasLayout = new javax.swing.GroupLayout(painelConsultasCadastradas);
        painelConsultasCadastradas.setLayout(painelConsultasCadastradasLayout);
        painelConsultasCadastradasLayout.setHorizontalGroup(
            painelConsultasCadastradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultasCadastradasLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        painelConsultasCadastradasLayout.setVerticalGroup(
            painelConsultasCadastradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultasCadastradasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitleConsultasCadastradas.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleConsultasCadastradas.setText("CONSULTAS CADASTRADAS");
        painelTitleConsultasCadastradas.add(lblTitleConsultasCadastradas);

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCadastrar);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelConsultasCadastradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(523, 523, 523)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelConsultasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdActionPerformed
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Consulta newConsulta = this.camposToConsulta();
        
        if (this.consultasCadastradas.add(newConsulta)) {
            JOptionPane.showMessageDialog(this, "Consulta cadastrada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Essa consulta já está cadastrada");
        }
        
        this.clearCampos();
        
        this.edtConsultasCadastradas.setText(consultasCadastradas.toString());
        this.saveToJSON();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextArea edtConsultasCadastradas;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleConsultasCadastradas;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelConsultasCadastradas;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleConsultasCadastradas;
    // End of variables declaration//GEN-END:variables
}
