/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.cadconsultas.gui.dlg.dlgConsultas;

import com.mycompany.cadconsultas.file.FilePersistence;
import com.mycompany.cadconsultas.file.JSONConsultasService;
import com.mycompany.cadconsultas.listas.ListConsultas;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class DlgRemoveConsultas extends javax.swing.JDialog {
    private final ListConsultas consultasCadastradas;
    
    /**
     * Creates new form DlgRemoveConsultas
     * @param parent
     * @param modal
     * @param consultasCadastradas
     */
    public DlgRemoveConsultas(java.awt.Frame parent, boolean modal, ListConsultas consultasCadastradas) {
        super(parent, modal);
        initComponents();
        
        this.consultasCadastradas = consultasCadastradas;
        this.clearCampos();
        this.edtConsultasCadastradas.setText(this.consultasCadastradas.toString());
    }
    
    private void saveToJSON() {
        String path = "Consultas.json";
        String data = JSONConsultasService.consultasToJSON(this.consultasCadastradas);
        FilePersistence.saveToFile(data, path);
    }
    
    private void clearCampos() {
        this.edtRemovedId.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        painelIdConsultaRemovida = new javax.swing.JPanel();
        lblRemovedId = new javax.swing.JLabel();
        edtRemovedId = new javax.swing.JTextField();
        painelTitleConsultasCadastradas = new javax.swing.JPanel();
        lblTitleConsultasCadastradas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtConsultasCadastradas = new javax.swing.JTextArea();
        painelBtns = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitle.setText("REMOVENDO CONSULTAS");
        painelTitle.add(lblTitle);

        lblRemovedId.setText("ID da consulta que vai ser removida");

        edtRemovedId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRemovedIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelIdConsultaRemovidaLayout = new javax.swing.GroupLayout(painelIdConsultaRemovida);
        painelIdConsultaRemovida.setLayout(painelIdConsultaRemovidaLayout);
        painelIdConsultaRemovidaLayout.setHorizontalGroup(
            painelIdConsultaRemovidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIdConsultaRemovidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelIdConsultaRemovidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRemovedId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtRemovedId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelIdConsultaRemovidaLayout.setVerticalGroup(
            painelIdConsultaRemovidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIdConsultaRemovidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemovedId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtRemovedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleConsultasCadastradas.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitleConsultasCadastradas.setText("CONSULAS CADASTRADAS");
        painelTitleConsultasCadastradas.add(lblTitleConsultasCadastradas);

        edtConsultasCadastradas.setColumns(20);
        edtConsultasCadastradas.setRows(5);
        jScrollPane1.setViewportView(edtConsultasCadastradas);
        this.edtConsultasCadastradas.setEditable(false);

        painelBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnRemove.setText("REMOVER");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        painelBtns.add(btnRemove);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelBtns.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelIdConsultaRemovida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTitleConsultasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelIdConsultaRemovida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                        .addComponent(painelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtRemovedIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRemovedIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRemovedIdActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String nomeRemovido = this.edtRemovedId.getText();
        
        if (this.consultasCadastradas.remove(nomeRemovido)) {
            JOptionPane.showMessageDialog(this, "Consulta removida com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Essa consulta não foi cadastrada no sistema");
        }
        
        this.clearCampos();
        this.edtConsultasCadastradas.setText(this.consultasCadastradas.toString());
        this.saveToJSON();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.clearCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JTextArea edtConsultasCadastradas;
    private javax.swing.JTextField edtRemovedId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRemovedId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleConsultasCadastradas;
    private javax.swing.JPanel painelBtns;
    private javax.swing.JPanel painelIdConsultaRemovida;
    private javax.swing.JPanel painelTitle;
    private javax.swing.JPanel painelTitleConsultasCadastradas;
    // End of variables declaration//GEN-END:variables
}
